# Generated by Django 4.2.11 on 2026-02-27 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyQRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qr', models.FileField(upload_to='myqrcode')),
            ],
        ),
    ]
